#!/usr/bin/env bash
set -Eeuo pipefail

SERVICE_USER="${SERVICE_USER:-osmanager}"
SUDOERS_PATH="/etc/sudoers.d/osmanager"

usage() {
  echo "用法：sudo $0 app-a.service [nginx.service ...]"
  echo "仅为列出的 systemd 服务生成 start/stop/restart 精确授权。"
}

[[ "$(id -u)" -eq 0 ]] || { echo "请使用 sudo $0" >&2; exit 1; }
[[ "$#" -gt 0 ]] || { usage; exit 1; }
command -v visudo >/dev/null || { echo "未找到 visudo" >&2; exit 1; }

for service in "$@"; do
  [[ "$service" =~ ^[A-Za-z0-9_.@:-]+\.service$ ]] || { echo "非法服务名：$service" >&2; exit 1; }
done

tmp="$(mktemp /etc/sudoers.d/osmanager.XXXXXX)"
trap 'rm -f "$tmp"' EXIT
{
  echo "# Generated by OSManager configure-sudo.sh"
  echo -n "Cmnd_Alias OSMANAGER_SERVICES = "
  first=1
  for service in "$@"; do
    for action in start stop restart; do
      [[ "$first" -eq 1 ]] || echo -n ", "
      echo -n "/usr/bin/systemctl $action $service"
      first=0
    done
  done
  echo
  echo "$SERVICE_USER ALL=(root) NOPASSWD: OSMANAGER_SERVICES"
} > "$tmp"
chmod 0440 "$tmp"
visudo -cf "$tmp"
install -o root -g root -m 0440 "$tmp" "$SUDOERS_PATH"
echo "已安装受限 sudo 规则：$SUDOERS_PATH"
