<script setup lang="ts">
import { computed, onMounted, onUnmounted, reactive, ref } from 'vue'
import MetricChart from './components/MetricChart.vue'
import { fmtBytes, fmtTime, post, request, token } from './api'

type User = { id:number,userName:string,displayName:string,role:string }
const currentUser = ref<User|null>(null), login = reactive({ userName:'admin', password:'ChangeMe!123' })
const busy = ref(false), notice = ref(''), error = ref(''), view = ref('dashboard'), resources = ref<any>({directories:[],services:[]})
const menu = [
  ['dashboard','◫','运行概览'], ['files','⌗','文件发布'], ['logs','≡','日志搜索'], ['services','◉','服务管理'],
  ['processes','⌁','进程管理'], ['configs','⌘','配置审批'], ['audit','◇','审计记录'], ['users','⊕','用户管理']
]
const title = computed(() => menu.find(x => x[0] === view.value)?.[2] || '')
const dashboard = ref<any>({ metrics:[],services:[] }), files = ref<any>({items:[]}), deployments = ref<any[]>([]), services = ref<any[]>([]), processes = ref<any[]>([]), audits = ref<any[]>([]), users = ref<any[]>([]), changes = ref<any[]>([]), results = ref<any[]>([]), journal = ref<any[]>([])
const currentRoot = ref(''), currentPath = ref(''), selectedFile = ref<File|null>(null)
const logForm = reactive({ rootId:'', path:'', start:localDate(-1), end:localDate(0), query:'', regex:false, caseSensitive:false, limit:1000 })
const journalForm = reactive({ service:'', start:localDate(-1), end:localDate(0), query:'', priority:'', limit:1000 })
const configEdit = reactive({ rootId:'', path:'', content:'', version:'', reason:'' })
let timer:number|undefined, journalAbort:AbortController|undefined
const following = ref(false)

function localDate(hours:number) { const d = new Date(Date.now()+hours*3600000); d.setMinutes(d.getMinutes()-d.getTimezoneOffset()); return d.toISOString().slice(0,16) }
function flash(message:string) { notice.value=message; setTimeout(()=>notice.value='',3000) }
async function execute(fn:()=>Promise<void>) { busy.value=true; error.value=''; try { await fn() } catch(e:any){ error.value=e.message } finally { busy.value=false } }
async function signIn(){ await execute(async()=>{ const r=await post('/auth/login',login); token.set(r.token); currentUser.value=r.user; await boot() }) }
function signOut(){ token.clear(); currentUser.value=null; if(timer) clearInterval(timer) }
async function boot(){ currentUser.value=await request('/auth/me'); resources.value=await request('/resources'); currentRoot.value ||= resources.value.directories[0]?.id || ''; logForm.rootId ||= currentRoot.value; journalForm.service ||= resources.value.services[0] || ''; await load('dashboard'); timer=window.setInterval(()=>{ if(view.value==='dashboard') refreshDashboard() },5000) }
async function load(next:string){ view.value=next; await execute(async()=>{ if(next==='dashboard') await refreshDashboard(); if(next==='files') await loadFiles(); if(next==='services') services.value=await request('/services'); if(next==='processes') processes.value=await request('/processes'); if(next==='configs') changes.value=await request('/configs/changes'); if(next==='audit') audits.value=await request('/audit'); if(next==='users') users.value=await request('/users') }) }
async function refreshDashboard(){ dashboard.value=await request('/dashboard') }
async function loadFiles(path=currentPath.value){ currentPath.value=path; files.value=await request(`/files?rootId=${encodeURIComponent(currentRoot.value)}&path=${encodeURIComponent(path)}`); deployments.value=await request('/deployments') }
async function openItem(item:any){ if(item.isDirectory){await loadFiles(item.path);return} await execute(async()=>{const response=await fetch(`/api/files/download?rootId=${encodeURIComponent(currentRoot.value)}&path=${encodeURIComponent(item.path)}`,{headers:{Authorization:`Bearer ${token.get()}`}});if(!response.ok)throw new Error('文件下载失败');const url=URL.createObjectURL(await response.blob());const a=document.createElement('a');a.href=url;a.download=item.name;a.click();URL.revokeObjectURL(url)}) }
async function deploy(){ if(!selectedFile.value) return; await execute(async()=>{ const fd=new FormData();fd.append('file',selectedFile.value!); const path=currentPath.value ? `${currentPath.value}/${selectedFile.value!.name}` : selectedFile.value!.name; const r=await post(`/files/deploy?rootId=${encodeURIComponent(currentRoot.value)}&path=${encodeURIComponent(selectedFile.value!.name.endsWith('.zip')?currentPath.value:path)}`,fd); let message='发布完成';if(r.canRestart&&confirm(`发布完成，是否立即重启 ${r.relatedService}？`)){await post(`/services/${encodeURIComponent(r.relatedService)}/action`,{action:'restart'});message=`发布完成，${r.relatedService} 已重启`}flash(message); selectedFile.value=null; await loadFiles() }) }
async function rollback(id:number){ if(!confirm('确认回滚这次发布？当前文件将被替换。'))return; await execute(async()=>{await post(`/deployments/${id}/rollback`);flash('回滚完成');await loadFiles()})}
async function searchLogs(){ await execute(async()=>{results.value=await post('/logs/search',{...logForm,start:new Date(logForm.start),end:new Date(logForm.end)})}) }
async function serviceAction(name:string,action:string){ if(!confirm(`确认${action==='stop'?'停止':action==='start'?'启动':'重启'} ${name}？`))return; await execute(async()=>{await post(`/services/${encodeURIComponent(name)}/action`,{action});flash('服务操作成功');services.value=await request('/services')}) }
async function killProcess(p:any,force=false){ if(!confirm(`确认${force?'强制':''}终止进程 ${p.pid} / ${p.name}？`))return;await execute(async()=>{await post(`/processes/${p.pid}/terminate?force=${force}`);flash('终止信号已发送');processes.value=await request('/processes')})}
async function queryJournal(){await execute(async()=>{journal.value=await post('/journal/query',{...journalForm,start:new Date(journalForm.start),end:new Date(journalForm.end)})})}
async function toggleFollow(){if(following.value){journalAbort?.abort();following.value=false;return}if(!journalForm.service)return;journalAbort=new AbortController();following.value=true;journal.value=[];try{const r=await fetch(`/api/journal/follow?service=${encodeURIComponent(journalForm.service)}`,{headers:{Authorization:`Bearer ${token.get()}`},signal:journalAbort.signal});if(!r.ok)throw new Error('实时日志连接失败');const reader=r.body!.getReader();const decoder=new TextDecoder();let buffer='';while(true){const {done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const blocks=buffer.split('\n\n');buffer=blocks.pop()||'';for(const block of blocks){const raw=block.split('\n').find(x=>x.startsWith('data: '))?.slice(6);if(!raw)continue;try{const x=JSON.parse(raw);journal.value.push({timestamp:x.__REALTIME_TIMESTAMP?new Date(Number(x.__REALTIME_TIMESTAMP)/1000):new Date(),priority:x.PRIORITY||'',message:x.MESSAGE||x.message||''});if(journal.value.length>5000)journal.value.shift()}catch{}}}}catch(e:any){if(e.name!=='AbortError')error.value=e.message}finally{following.value=false}}
function downloadJournal(){const text=journal.value.map(x=>`${fmtTime(x.timestamp)} [P${x.priority}] ${x.message}`).join('\n');const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`${journalForm.service||'journal'}-${Date.now()}.log`;a.click();URL.revokeObjectURL(url)}
async function readConfig(){await execute(async()=>{const r=await request(`/configs/content?rootId=${encodeURIComponent(configEdit.rootId)}&path=${encodeURIComponent(configEdit.path)}`);configEdit.content=r.content;configEdit.version=r.version})}
async function submitConfig(){await execute(async()=>{await post('/configs/changes',configEdit);flash('修改已提交审批');changes.value=await request('/configs/changes')})}
async function review(id:number,decision:string){const comment=prompt('审批意见（可选）')||'';await execute(async()=>{await post(`/configs/changes/${id}/review`,{decision,comment});flash('审批完成');changes.value=await request('/configs/changes')})}
async function applyConfig(id:number){if(!confirm('确认将已批准的内容写入配置文件？'))return;await execute(async()=>{await post(`/configs/changes/${id}/apply`);const change=changes.value.find(x=>x.id===id);const service=resources.value.directories.find((x:any)=>x.id===change?.root_id)?.relatedService;let message='配置已应用';if(service&&confirm(`配置已应用，是否立即重启 ${service}？`)){await post(`/services/${encodeURIComponent(service)}/action`,{action:'restart'});message=`配置已应用，${service} 已重启`}flash(message);changes.value=await request('/configs/changes')})}
async function createUser(e:Event){const form=e.target as HTMLFormElement;const data=Object.fromEntries(new FormData(form));await execute(async()=>{await post('/users',data);flash('用户已创建');form.reset();users.value=await request('/users')})}
async function changePassword(e:Event){const form=e.target as HTMLFormElement;const data=Object.fromEntries(new FormData(form));await execute(async()=>{await post('/auth/password',data);flash('密码已修改');form.reset()})}
onMounted(()=>{if(token.get())boot().catch(()=>signOut())});onUnmounted(()=>{if(timer)clearInterval(timer);journalAbort?.abort()})
</script>

<template>
  <div v-if="!currentUser" class="login-shell">
    <div class="login-grid"></div><section class="login-card">
      <div class="brand-mark">OS<span>/</span>M</div><p class="eyebrow">LOCAL HOST CONTROL</p>
      <h1>主机在手，<br><em>边界清晰。</em></h1><p class="muted">面向 Linux 主机的受限运维控制台</p>
      <form @submit.prevent="signIn" class="login-form"><label>账户<input v-model="login.userName" autocomplete="username"></label><label>密码<input v-model="login.password" type="password" autocomplete="current-password"></label><button class="primary" :disabled="busy">{{busy?'正在验证…':'进入控制台 →'}}</button></form>
      <p v-if="error" class="error">{{error}}</p><p class="login-foot">首次登录后请立即修改默认密码</p>
    </section>
  </div>
  <div v-else class="app-shell">
    <aside class="sidebar"><div class="logo"><b>OS<span>/</span>M</b><small>HOST CONTROL</small></div><nav><button v-for="m in menu" :key="m[0]" :class="{active:view===m[0]}" @click="load(m[0])"><i>{{m[1]}}</i>{{m[2]}}</button></nav><div class="sidebar-foot"><span class="pulse"></span><div><b>{{resources.platform==='linux'?'主机在线':'开发模式'}}</b><small>{{resources.demoMode?'命令不会执行':'受限操作已启用'}}</small></div></div></aside>
    <main><header><div><p class="eyebrow">OSMANAGER / {{view.toUpperCase()}}</p><h2>{{title}}</h2></div><div class="operator"><span>{{currentUser.displayName}}</span><small>{{currentUser.role}}</small><button @click="signOut">退出</button></div></header>
      <div v-if="error" class="toast error">{{error}}<button @click="error=''">×</button></div><div v-if="notice" class="toast success">{{notice}}</div><div v-if="busy" class="progress"></div>
      <section v-if="view==='dashboard'" class="page dashboard">
        <div class="hero panel"><div><p class="eyebrow">NODE / {{dashboard.host}}</p><h3>系统运行平稳</h3><p>{{dashboard.os}}</p></div><div class="hero-stat"><small>UPTIME</small><strong>{{Math.floor((dashboard.uptimeSeconds||0)/3600)}}<i>h</i></strong></div></div>
        <div class="metric-grid"><article class="metric panel"><div><span>CPU 使用率</span><strong>{{dashboard.metrics.at(-1)?.cpu?.toFixed(1)||'0.0'}}<i>%</i></strong></div><MetricChart :points="dashboard.metrics" field="cpu" color="#1f883d"/></article><article class="metric panel"><div><span>内存使用率</span><strong>{{dashboard.metrics.at(-1)?.memory?.toFixed(1)||'0.0'}}<i>%</i></strong></div><MetricChart :points="dashboard.metrics" field="memory" color="#0969da"/></article></div>
        <div class="panel table-panel"><div class="panel-title"><h3>受管服务</h3><span>{{dashboard.services.length}} SERVICES</span></div><table><thead><tr><th>服务</th><th>状态</th><th>子状态</th><th>主进程</th><th>启动时间</th></tr></thead><tbody><tr v-for="s in dashboard.services"><td class="mono">{{s.service}}</td><td><span class="badge" :class="s.activeState==='active'?'ok':'warn'">{{s.activeState}}</span></td><td>{{s.subState}}</td><td>{{s.mainPid}}</td><td>{{s.since||'—'}}</td></tr><tr v-if="!dashboard.services.length"><td colspan="5" class="empty">尚未配置受管服务</td></tr></tbody></table></div>
      </section>
      <section v-else-if="view==='files'" class="page"><div class="toolbar panel"><select v-model="currentRoot" @change="loadFiles('')"><option v-for="r in resources.directories" :value="r.id">{{r.name}}</option></select><span class="path">/{{currentPath}}</span><label class="file-pick"><input type="file" @change="selectedFile=($event.target as HTMLInputElement).files?.[0]||null">{{selectedFile?.name||'选择文件或 ZIP'}}</label><button class="primary small" :disabled="!selectedFile" @click="deploy">发布</button></div><div class="split"><div class="panel table-panel"><div class="panel-title"><h3>文件</h3><button v-if="currentPath" class="ghost" @click="loadFiles(currentPath.split('/').slice(0,-1).join('/'))">↑ 返回上级</button></div><table><thead><tr><th>名称</th><th>大小</th><th>修改时间</th></tr></thead><tbody><tr v-for="f in files.items" @dblclick="openItem(f)" class="clickable"><td><b>{{f.isDirectory?'▰':'▤'}} {{f.name}}</b></td><td>{{f.isDirectory?'—':fmtBytes(f.size)}}</td><td>{{fmtTime(f.modified)}}</td></tr></tbody></table></div><div class="panel table-panel"><div class="panel-title"><h3>最近发布</h3></div><div v-for="d in deployments" class="deploy-row"><div><b>#{{d.id}} · {{d.relative_path}}</b><small>{{d.user_name}} · {{fmtTime(d.created_at)}}</small></div><span class="badge" :class="d.status==='Succeeded'?'ok':'warn'">{{d.status}}</span><button v-if="d.status==='Succeeded'" class="danger-text" @click="rollback(d.id)">回滚</button></div><p v-if="!deployments.length" class="empty">暂无发布记录</p></div></div></section>
      <section v-else-if="view==='logs'" class="page"><div class="panel query"><div class="panel-title"><h3>普通文件日志</h3><span>MAX 7 DAYS</span></div><div class="form-grid"><label>日志根目录<select v-model="logForm.rootId"><option v-for="r in resources.directories" :value="r.id">{{r.name}}</option></select></label><label>相对目录<input v-model="logForm.path" placeholder="logs"></label><label>开始时间<input v-model="logForm.start" type="datetime-local"></label><label>结束时间<input v-model="logForm.end" type="datetime-local"></label><label class="wide">搜索内容<input v-model="logForm.query" placeholder="错误信息或关键字"></label><button class="primary" @click="searchLogs">开始搜索</button></div></div><div class="panel log-output"><div class="panel-title"><h3>匹配结果</h3><span>{{results.length}} MATCHES</span></div><div v-for="r in results" class="log-line"><span>{{r.file}}:{{r.line}}</span><code>{{r.content}}</code></div><p v-if="!results.length" class="empty">等待搜索条件</p></div></section>
      <section v-else-if="view==='services'" class="page"><div class="service-grid"><article v-for="s in services" class="panel service-card"><div><span class="service-icon">◉</span><span class="badge" :class="s.activeState==='active'?'ok':'warn'">{{s.activeState}}</span></div><h3>{{s.service}}</h3><p>PID {{s.mainPid}} · {{s.subState}}</p><div class="actions"><button @click="serviceAction(s.service,'start')">启动</button><button @click="serviceAction(s.service,'restart')">重启</button><button class="danger-text" @click="serviceAction(s.service,'stop')">停止</button></div></article><div v-if="!services.length" class="panel empty big">尚未在 appsettings.json 中配置受管服务</div></div><div class="panel query"><div class="panel-title"><h3>Journal 日志</h3><div class="actions"><span v-if="following" class="live">● LIVE</span><button v-if="journal.length" class="ghost" @click="downloadJournal">下载日志</button></div></div><div class="form-grid"><label>服务<select v-model="journalForm.service"><option v-for="s in resources.services">{{s}}</option></select></label><label>开始<input v-model="journalForm.start" type="datetime-local"></label><label>结束<input v-model="journalForm.end" type="datetime-local"></label><label>关键词<input v-model="journalForm.query"></label><button class="primary" @click="queryJournal">历史查询</button><button class="ghost" @click="toggleFollow">{{following?'停止实时':'实时滚动'}}</button></div><div class="journal"><div v-for="j in journal" class="log-line"><span>{{fmtTime(j.timestamp)}} · P{{j.priority}}</span><code>{{j.message}}</code></div></div></div></section>
      <section v-else-if="view==='processes'" class="page panel table-panel"><div class="panel-title"><h3>进程快照</h3><button class="ghost" @click="load('processes')">刷新</button></div><table><thead><tr><th>PID</th><th>进程</th><th>内存</th><th>CPU 时间</th><th>启动时间</th><th></th></tr></thead><tbody><tr v-for="p in processes"><td class="mono">{{p.pid}}</td><td><b>{{p.name}}</b></td><td>{{fmtBytes(p.memory)}}</td><td>{{p.cpu.toFixed(1)}}s</td><td>{{p.started?fmtTime(p.started):'—'}}</td><td class="actions"><button class="danger-text" @click="killProcess(p)">终止</button><button class="danger-text" @click="killProcess(p,true)">强制</button></td></tr></tbody></table></section>
      <section v-else-if="view==='configs'" class="page"><div class="split"><div class="panel query"><div class="panel-title"><h3>提交配置修改</h3><span>APPROVAL REQUIRED</span></div><label>管理目录<select v-model="configEdit.rootId"><option value="" disabled>请选择</option><option v-for="r in resources.directories" :value="r.id">{{r.name}}</option></select></label><label>相对文件路径<div class="inline"><input v-model="configEdit.path" placeholder="config/app.json"><button @click="readConfig">读取</button></div></label><label>修改原因<input v-model="configEdit.reason" placeholder="说明变更目的"></label><label>配置内容<textarea v-model="configEdit.content" spellcheck="false"></textarea></label><button class="primary" @click="submitConfig">提交审批</button></div><div class="panel table-panel"><div class="panel-title"><h3>审批队列</h3><span>{{changes.length}} RECORDS</span></div><div v-for="c in changes" class="change-row"><div><b>#{{c.id}} · {{c.relative_path}}</b><small>{{c.submitter}} · {{c.reason||'未说明原因'}}</small></div><span class="badge" :class="c.status==='Applied'?'ok':c.status==='Rejected'?'bad':'warn'">{{c.status}}</span><div class="actions"><button v-if="c.status==='PendingApproval'" @click="review(c.id,'approve')">批准</button><button v-if="c.status==='PendingApproval'" class="danger-text" @click="review(c.id,'reject')">拒绝</button><button v-if="c.status==='Approved'" class="primary small" @click="applyConfig(c.id)">应用</button></div></div></div></div></section>
      <section v-else-if="view==='audit'" class="page panel table-panel"><div class="panel-title"><h3>审计事件</h3><span>IMMUTABLE TRAIL</span></div><table><thead><tr><th>时间</th><th>操作人</th><th>动作</th><th>目标</th><th>结果</th><th>来源</th></tr></thead><tbody><tr v-for="a in audits"><td>{{fmtTime(a.created_at)}}</td><td>{{a.user_name}}</td><td class="mono">{{a.action}}</td><td>{{a.target}}</td><td><span class="badge" :class="a.success?'ok':'bad'">{{a.success?'成功':'失败'}}</span></td><td>{{a.ip}}</td></tr></tbody></table></section>
      <section v-else-if="view==='users'" class="page"><div class="split"><div><form class="panel query" @submit.prevent="createUser"><div class="panel-title"><h3>创建本地账户</h3></div><label>用户名<input name="userName" required></label><label>显示名称<input name="displayName" required></label><label>初始密码<input name="password" type="password" minlength="10" required></label><label>角色<select name="role"><option>Viewer</option><option>Editor</option><option>Approver</option><option>Operator</option><option>Admin</option></select></label><button class="primary">创建账户</button></form><form class="panel query password-card" @submit.prevent="changePassword"><div class="panel-title"><h3>修改我的密码</h3></div><label>当前密码<input name="currentPassword" type="password" required></label><label>新密码<input name="newPassword" type="password" minlength="10" required></label><button class="ghost">更新密码</button></form></div><div class="panel table-panel"><div class="panel-title"><h3>用户</h3></div><div v-for="u in users" class="user-row"><span class="avatar">{{u.display_name.slice(0,1)}}</span><div><b>{{u.display_name}}</b><small>@{{u.username}}</small></div><span class="badge">{{u.role}}</span></div></div></div></section>
    </main>
  </div>
</template>
